version: '3'
services:
  authapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://*:80
    ports:
      - "80"
  authresourcesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://*:80
    ports:
      - "80"